---
fixtures:
  repositories:
    common: "git://github.com/simp/pupmod-simp-common"
    stdlib:
      repo : "git://github.com/simp/puppetlabs-stdlib"
      branch : "simp-master"
    augeasproviders :
      repo : "git://github.com/simp/augeasproviders"
      branch : "simp-master"
    augeasproviders_core :
      repo : "git://github.com/simp/augeasproviders_core"
      branch : "simp-master"
    augeasproviders_sysctl:
      repo : "git://github.com/simp/augeasproviders_sysctl"
      branch : "simp-master"
  symlinks:
    sysctl: "#{source_dir}"
