---
fixtures:
  repositories:
    augeasproviders:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders
    augeasproviders_core:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_core
    augeasproviders_sysctl:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_sysctl
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    sysctl: "#{source_dir}"
